- hosts: localhost
  tasks:
    - shell: cat loop.yml
      register: result
   
    - set_fact:
        myvar: "{{ result.stdout | from_yaml }}"

    - debug:
        msg: "data: {{ item.key }} - {{ item.value }}"
      with_items:
        "{{ lookup('dict',myvar[0])}}"

    - debug:
        msg: "{{ undefined | default('set_a_var')}}"
